#filter info
view:         Visualizar
add:          Adicionar ao bloqueador de an&uacute;ncios
url:          https://raw.githubusercontent.com/easylistbrasil/easylistbrasil/filtro/easylistbrasil.txt
repository:   https://github.com/easylistbrasil/easylistbrasil

#download
adblock:      https://adblockplus.org/
ublock:       /ublock.html

# Setup
title:        EasyList Brasil
description:  Easylist Brasil é um filtro para adblock que remove anúncios em sites do Brasil
keywords:     Easylist, Easylist Brasil, subscription adblock, filtro adblock, remover propaganda em sites de filmes
tagline:      Filtro para seu bloqueador de an&uacute;ncios
baseurl:      ""
paginate:     1
locale:       "pt-BR"

# About/contact
author:
  name:       Author name
  url:        https://easylistbrasil.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
