#filter info
view:         Visualizar
view-menu:    Visualizar no Github
add:          Adicionar ao bloqueador de an&uacute;ncios
issue:        Reportar an&uacute;ncio
url:          https://raw.githubusercontent.com/easylistbrasil/easylistbrasil/filtro/easylistbrasil.txt
repository:   https://github.com/easylistbrasil/easylistbrasil
issue-url:    https://github.com/easylistbrasil/easylistbrasil/issues/new

#changelog
repo-log:     easylistbrasil
user-log:     easylistbrasil

#posts
androidname:  Android
androidlink:  /main/2018/08/22/android.html

#download
adblock-menu:  Download Adblock Plus
adblock-url:   https://adblockplus.org/
ublock-menu:   Download uBlock Origin
ublock-url:    /ublock.html

# Setup
title:        EasyList Brasil
description:  Easylist Brasil é um filtro para adblock que remove anúncios em sites do Brasil
keywords:     Easylist, Easylist Brasil, subscription adblock, filtro adblock, remover propaganda em sites de filmes
tagline:      Filtro para seu bloqueador de an&uacute;ncios
baseurl:      "/"
paginate:     1
locale:       "pt-BR"

# About/contact
author:
  name:       Author name
  url:        https://easylistbrasil.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
