# Setup
title:        EasyList Brasil
tagline:      Filtro para seu bloqueador de an&uacute;ncios
baseurl:      ""
paginate:     1
locale:       "pt-BR"

# About/contact
author:
  name:       Author name
  url:        https://easylistbrasil.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
